name: KeepInvIndividual
version: ${plugin_version}
author: Niestrat99
description: Allow individual players to keep their inventory on death without using the gamerule.
main: io.github.niestrat99.keepinvindividual.KeepInvIndividual
api-version: 1.20

permissions:
  ki.admin.cmd.on:
    default: op

  ki.admin.cmd.off:
    default: op

  ki.admin.cmd.other:
    default: op

  ki.admin.cmd.reload:
    default: op

  ki.admin.cmd.list:
    default: op

  ki.admin.cmd.help:
    default: op

  ki.keepxp:
    default: op

commands:
  keepinventory:
    description: Used to enable/disable keepInventory for players, reload config files or check a list.